# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mdownload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mdownload.proto',
  package='protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fmdownload.proto\x12\x08protocol\"*\n\x0brequestData\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06outdir\x18\x02 \x01(\t\")\n\x0cresponseData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2F\n\tmDownload\x12\x39\n\x06\x61\x64\x64Uri\x12\x15.protocol.requestData\x1a\x16.protocol.responseData\"\x00\x62\x06proto3')
)




_REQUESTDATA = _descriptor.Descriptor(
  name='requestData',
  full_name='protocol.requestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='protocol.requestData.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outdir', full_name='protocol.requestData.outdir', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=71,
)


_RESPONSEDATA = _descriptor.Descriptor(
  name='responseData',
  full_name='protocol.responseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protocol.responseData.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='protocol.responseData.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['requestData'] = _REQUESTDATA
DESCRIPTOR.message_types_by_name['responseData'] = _RESPONSEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

requestData = _reflection.GeneratedProtocolMessageType('requestData', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDATA,
  '__module__' : 'mdownload_pb2'
  # @@protoc_insertion_point(class_scope:protocol.requestData)
  })
_sym_db.RegisterMessage(requestData)

responseData = _reflection.GeneratedProtocolMessageType('responseData', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATA,
  '__module__' : 'mdownload_pb2'
  # @@protoc_insertion_point(class_scope:protocol.responseData)
  })
_sym_db.RegisterMessage(responseData)



_MDOWNLOAD = _descriptor.ServiceDescriptor(
  name='mDownload',
  full_name='protocol.mDownload',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=116,
  serialized_end=186,
  methods=[
  _descriptor.MethodDescriptor(
    name='addUri',
    full_name='protocol.mDownload.addUri',
    index=0,
    containing_service=None,
    input_type=_REQUESTDATA,
    output_type=_RESPONSEDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MDOWNLOAD)

DESCRIPTOR.services_by_name['mDownload'] = _MDOWNLOAD

# @@protoc_insertion_point(module_scope)
